### ISSUE TITLE
Add textDocument/publishDiagnostics

### ISSUE THREAD

**Issue by angelozerr** [prabirshrestha/typescript-language-server#1]
Please add `textDocument/publishDiagnostics` feature. Thanks!

**Comment by prabirshrestha** [comment]
Currently I'm mainly focusing on features that is supported by `vim-lsp` so it will take me some time before I work on this feature since `vim-lsp` doesn't support diagnostics yet. But if anyone sends a PR I would be happy to merge it.

**Comment by angelozerr** [comment]
Thanks @prabirshrestha for you answer! I will try to do a PR if I decide to use typescript-language-server. Many thanks for your work!

**Comment by prabirshrestha** [comment]
available in https://github.com/theia-ide/typescript-language-server
