### ISSUE TITLE
CodeLens support

### ISSUE THREAD

**Issue by angelozerr** [prabirshrestha/typescript-language-server#9]
tsserver doesn't supports CodeLens, but we could implement `textDocument/codeLens` and `codeLens/resolve` like VSCode does for [References CodeLens](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/referencesCodeLensProvider.ts) and [Implementations CodeLens](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/implementationsCodeLensProvider.ts)

**Comment by prabirshrestha** [comment]
refer to https://github.com/theia-ide/typescript-language-server/issues/5
